### ISSUE TITLE
HAML-issue: facebook view helpers (with an attached form_for)

### ISSUE THREAD

**Issue by grimen** [grimen/devise_facebook_connectable#5]
Only appears in HAML:

<pre>
/Users/grimen/Development/examples/devise_plugin/devise_example/vendor/plugins/devise_facebook_connectable/lib/devise_facebook_connectable/view_helpers.rb:79:in `facebook_login_or_connect_link'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_view/helpers/capture_helper.rb:39:in `call'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_view/helpers/capture_helper.rb:39:in `capture_without_haml'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_view/helpers/capture_helper.rb:129:in `with_output_buffer'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_view/helpers/capture_helper.rb:39:in `capture_without_haml'
/Library/Ruby/Gems/1.8/gems/haml-2.2.8/lib/haml/helpers/action_view_mods.rb:88:in `capture'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_view/helpers/tag_helper.rb:70:in `content_tag_without_haml'
/Library/Ruby/Gems/1.8/gems/haml-2.2.8/lib/haml/helpers/action_view_mods.rb:98:in `content_tag'
/Users/grimen/Development/examples/devise_plugin/devise_example/app/views/home/index.html.erb:3:in `_run_erb_app47views47home47index46html46erb'
/Library/Ruby/Gems/1.8/gems/actionpack-2.3.5/lib/action_view/renderable.rb:34:in `send'
</pre>

**Comment by grimen** [comment]
See README on how this can be avoided.
